# Generated by Django 5.1.6 on 2025-02-24 05:05

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='estadoActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estado', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='chicaMagica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('fecha_contratacion', models.DateField()),
                ('color', models.CharField(max_length=15)),
                ('imagen', models.ImageField(upload_to='chicas')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nombre')),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.ciudad')),
                ('id_estado_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.estadoactual')),
            ],
        ),
    ]
