# Generated by Django 5.1.6 on 2025-02-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_chicamagica_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicamagica',
            name='descripcion',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
