# Generated by Django 5.1.6 on 2025-02-26 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_chicamagica_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicamagica',
            name='id_ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chicas', to='tasks.ciudad'),
        ),
        migrations.AlterField(
            model_name='chicamagica',
            name='id_estado_actual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chicas', to='tasks.estadoactual'),
        ),
    ]
